version: '2.0'

services:

  wsic_api:
    container_name: wsic_api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/wsic
    environment:
      - DB_HOST=wsic_db
      - DB_PORT=5432

  wsic_db:
    container_name: wsic_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432